var LISTE_INSIGNE = [
"Appétit",
"Crépuscule",
"Minuit",
"Aube",
"Nuage",
"Pluie",
"Tonnerre",
"Neige",
"Blizzard",
"Sécheresse",
"Tempête de Sable",
"Brume",
"Pêche",
"Curry",
"Sociabilité",
"Espièglerie",
"Insouciance",
"Nervosité",
"Enthousiasme",
"Charisme",
"Sang-Froid",
"Sang-Chaud",
"Inattention",
"Bonheur",
"Colère",
"Rire",
"Pleurs",
"Bonne Humeur",
"Saute d'Humeur",
"Réflexion",
"Impulsivité",
"Ruse",
"Menace",
"Gentillesse",
"Panique",
"Entrain",
"Nonchalance",
"Fierté",
"Abattement",
"Discrétion",
"Frime",
"Énergie",
"Blessure",
"Rareté",
"Surpuissant",
"Amitié",
"Gourmet",
"Ramassage",
"Maxi",
"Mini",
"Dominant",
"Destin",
"Baron"
];

var LISTE_NATURE = [
"Assuré",
"Bizarre",
"Brave",
"Calme",
"Discret",
"Docile",
"Doux",
"Foufou",
"Gentil",
"Hardi",
"Jovial",
"Lâche",
"Malin",
"Malpoli",
"Mauvais",
"Modeste",
"Naïf",
"Pressé",
"Prudent",
"Pudique",
"Relax",
"Rigide",
"Sérieux",
"Solo",
"Timide"
];

var LISTE_INFO = [
	"Adore manger.",
	"S'assoupit souvent.",
	"Dort beaucoup.",
	"Éparpille les choses.",
	"Aime se détendre.",
	"Fier de sa puissance.",
	"Aime se démener.",
	"Un peu coléreux.",
	"Aime combattre.",
	"S'emporte facilement.",
	"Corps robuste.",
	"Sait encaisser les coups.",
	"Très obstiné.",
	"Bonne endurance.",
	"Persévérant.",
	"Extrêmement curieux.",
	"Coquin.",
	"Très astucieux.",
	"Souvent dans la lune.",
	"Très particulier.",
	"Très volontaire.",
	"Un peu vaniteux.",
	"Esprit rebelle.",
	"A horreur de perdre.",
	"Assez entêté.",
	"Aime courir.",
	"Attentif aux sons.",
	"Bête et impulsif.",
	"Aime faire le pitre.",
	"Fuit rapidement."
];

var LISTE_GROUPE_OEUF = [
    {nom:"Monstrueux",	sprites:"https://www.pokekalos.fr/pokedex/icons/eggs/monstrueux.png"},
	{nom:"Végétal",		sprites:"https://www.pokekalos.fr/pokedex/icons/eggs/vegetal.png"},
	{nom:"Draconique",	sprites:"https://www.pokekalos.fr/pokedex/icons/eggs/draconique.png"},
	{nom:"Aquatique 1",	sprites:"https://www.pokekalos.fr/pokedex/icons/eggs/aquatique1.png"},
	{nom:"Insectoïde",	sprites:"https://www.pokekalos.fr/pokedex/icons/eggs/insectoide.png"},	
	{nom:"Aérien",		sprites:"https://www.pokekalos.fr/pokedex/icons/eggs/aerien.png"},
    {nom:"Terrestre",	sprites:"https://www.pokekalos.fr/pokedex/icons/eggs/terrestre.png"},
	{nom:"Féerique",	sprites:"https://www.pokekalos.fr/pokedex/icons/eggs/feerique.png"},
	{nom:"Humanoïde",	sprites:"https://www.pokekalos.fr/pokedex/icons/eggs/humanoide.png"},
	{nom:"Aquatique 3",	sprites:"https://www.pokekalos.fr/pokedex/icons/eggs/aquatique3.png"},
	{nom:"Minéral",		sprites:"https://www.pokekalos.fr/pokedex/icons/eggs/mineral.png"},
	{nom:"Amorphe",		sprites:"https://www.pokekalos.fr/pokedex/icons/eggs/amorphe.png"},
	{nom:"Aquatique 2",	sprites:"https://www.pokekalos.fr/pokedex/icons/eggs/aquatique2.png"},
	{nom:"Métamorph",	sprites:"https://www.pokekalos.fr/pokedex/icons/eggs/metamorph.png"}
];

var ball = [
{name:"Appât Ball",		proba:0.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/lureball.png"},
{name:"Compét'Ball",	proba:0.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/sportball.png"},
{name:"Copain Ball",	proba:0.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/friendball.png"},
{name:"Love Ball",		proba:0.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/loveball.png"},
{name:"Lune Ball",		proba:0.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/moonball.png"},
{name:"Bis Ball",		proba:2.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/repeatball.png"},
{name:"Chrono Ball",	proba:2.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/timerball.png"},
{name:"Faiblo Ball",	proba:2.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/nestball.png"},
{name:"Filet Ball",		proba:2.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/netball.png"},
{name:"Honor Ball",		proba:2.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/premierball.png"},
{name:"Luxe Ball",		proba:2.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/luxuryball.png"},
{name:"Super Ball",		proba:21  , sprites:"https://www.serebii.net/itemdex/sprites/sv/greatball.png"},
{name:"Poké Ball",		proba:31.9, sprites:"https://www.serebii.net/itemdex/sprites/sv/pokeball.png"},
{name:"Hyper Ball",		proba:11  , sprites:"https://www.serebii.net/itemdex/sprites/sv/ultraball.png"},
{name:"Scuba Ball",		proba:2.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/diveball.png"},
{name:"Rapide Ball",	proba:2.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/quickball.png"},
{name:"Soin Ball",		proba:2.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/healball.png"},
{name:"Sombre Ball",	proba:2.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/duskball.png"},
{name:"Ultra Ball",		proba:2.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/beastball.png"},
{name:"Étrange Ball", 	proba:2.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/strangeball.png"},
{name:"Mémoire Ball", 	proba:1.0 , sprites:"https://www.serebii.net/itemdex/sprites/sv/cherishball.png"},
{name:"Masse Ball",		proba:0.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/heavyball.png"},
{name:"Niveau Ball",	proba:0.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/levelball.png"},
{name:"Speed Ball",		proba:0.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/fastball.png"},
{name:"Safari Ball",	proba:0.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/safariball.png"},
{name:"Rêve Ball",		proba:0.5 , sprites:"https://www.serebii.net/itemdex/sprites/sv/dreamball.png"},
{name:"Master Ball",	proba:0.1 , sprites:"https://www.serebii.net/itemdex/sprites/sv/masterball.png"}
];

